version: "3.8"

services:

  api:
    image: piotrkasperski/app-restrand-api:latest
    build:
      dockerfile: Dockerfile
      context: ./app-restrand-api
      # Only build development stage from Dockerfile
      target: production
      # Mount host dir to docker container
      # Mount api dir to docker container
      # Reflect file changes from host to docker
    volumes:
      - ./app-restrand-api:/usr/src/app
      - /usr/src/app/node_modules
      # RUN in debug mode: npm run start:debug
      # RUN in dev mode: npm run start:dev
    command: npm run start:dev
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      NODE_ENV: '${NODE_ENV}'
      JWT_SECRET: '${JWT_SECRET}'
      PORT: '${PORT}'
    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    image: piotrkasperski/app-restrand:latest
    depends_on:
      - postgres
    volumes:
      - ./app-restrand-frontend:/usr/frontend/src/app
      - /usr/frontend/src/app/node_modules
    ports:
      - 4200:80
    links:
      - api

  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.30
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - 5050:5050
